### ISSUE TITLE
doesn't work on windows 7

### ISSUE THREAD

**Issue by tx5** [arthurvr/gh-browse#2]
:-1:

**Comment by arthurvr** [comment]
What and when does fail? Is it throwing anything? Try to provide detailed information, instead of a simple thumbs down. Could you also let me know what node version you used? (`node -v`)

**Comment by tx5** [comment]
I'm using the latest node bro, v0.10.35

Why did you close this???? Did you even tested on Windows 7 to see if it works or not ?? such a lame ass thing to do...

**Comment by arthurvr** [comment]
> Why did you close this????

Because this isn't an appropriate bug report. Please provide more detailed information. I still don't know what version of npm, what repo, more info on your git config setup, where it is failing, if it is throwing anything?

What version are you using? latest or master?

I'm happy to investigate if I have a decent bug report. I can't do anything with a simple "it is failing".

**Comment by corvannoorloos** [comment]
Not exactly helpful, but haven't experienced any issues thus far, primarily running Win 7 Home Premium SP1 and node v0.10.35. Also using the h5bp repo as an example.

**Comment by arthurvr** [comment]
@corvannoorloos Thanks for letting us know. All info is useful for this kinds of issues.

**Comment by tx5** [comment]
how should i know what exact info you need... I told you that I'm using node and since node comes with npm well, I think you can figure out what npm version i am using ... i also did npm i -g npm.....

i was just trying out you package and i thought it would be useful for you to know about the issue..... but you don't seem to very nice and are just closing issues and are only "happy to investigate" not really trying to investigate ...

**Comment by arthurvr** [comment]
> but you don't seem to very nice and are just closing issues and are only "happy to investigate" not really trying to investigate ...

Just tried and there actually isn't an issue.

---------------------

Sorry but if you're wanting me to fix this at least give me the version of npm (`npm -v`) and the error it's throwing. How did you installed the package, using `npm install` or using the master branch?

**Comment by tx5** [comment]
bro did you even read my comment ? I kinda told you that I have the latest npm (npm i -g npm anyone???) ... can't believe people like you aren't ashamed to even put modules like this on the web

**Comment by arthurvr** [comment]
Well if you're not willing to give me info and seem to be really un-friendly, bye! (Also, come-on man, are you literally [making a github account to troll me](https://github.com/tx5?tab=activity)?)
